language: node_js

node_js:
  - 5.10

install:
  - npm install

  ## install the Cypress CLI Tools
  ## which gives us access to the
  ## `cypress` command used below
  - npm install -g cypress-cli

script:
  - npm run build

  ## now run cypress in CI mode
  ## which runs all of the tests
  ## and uses the CYPRESS_API_KEY
  ## environment var by default
  ## which you need to configure
  ## on Travis CI behind the scenes
  - cypress ci

  ## alternatively we could specify
  ## a specific secret key to use
  ## like this without having to
  ## configure anything in Travis CI:
  ## - cypress ci 703b33d9-a00e-4c66-90c2-40efc0fee2c6